# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YTCoverDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YTCoverDemo

  target 'YTCoverDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YTCoverDemoUITests' do
    # Pods for testing
  end

end
